// Builds overlay/book.js from the ECO tables in tools/eco/.
//
//   node tools/build-book.mjs
//
// Every line is replayed with the same chess.js the extension ships, so the
// position keys written here are exactly the ones the overlay looks up at
// runtime. Each position *along* a line is recorded, not just its last one, so
// a game is "in book" for as long as it is still following known theory.
//
// A position reached by several named lines keeps the name of the shortest one
// (lines are processed shortest first, and a name is never overwritten). That
// way early positions read "Sicilian Defense" rather than borrowing the name of
// some 20-ply variation that happens to run through them.

import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { Chess } from "../lib/chess.js";
import { bookKey } from "../overlay/book-key.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Read every eco/*.tsv as {eco, name, moves[]} rows. */
function readEco() {
  const dir = join(root, "tools", "eco");
  const rows = [];
  for (const file of readdirSync(dir).filter((f) => f.endsWith(".tsv")).sort()) {
    const lines = readFileSync(join(dir, file), "utf8").split("\n");
    for (const line of lines.slice(1)) {
      const [eco, name, pgn] = line.replace(/\r$/, "").split("\t");
      if (!eco || !name || !pgn) continue;
      const moves = pgn.split(/\s+/).filter((t) => t && !/^\d+\.+$/.test(t));
      if (moves.length) rows.push({ eco, name, moves });
    }
  }
  return rows;
}

const rows = readEco();
rows.sort((a, b) => a.moves.length - b.moves.length);

const names = [];
const nameIdx = new Map();
const book = new Map(); // position key -> index into names
let illegal = 0;

for (const row of rows) {
  const label = `${row.eco} ${row.name}`;
  let idx = nameIdx.get(label);
  if (idx === undefined) {
    idx = names.length;
    names.push(label);
    nameIdx.set(label, idx);
  }
  const chess = new Chess();
  for (const san of row.moves) {
    try {
      chess.move(san);
    } catch {
      illegal++;
      break;
    }
    const key = bookKey(chess.fen());
    if (!book.has(key)) book.set(key, idx);
  }
}

// Drop names no position ended up pointing at, then renumber.
const used = new Set(book.values());
const keptNames = [];
const remap = new Map();
names.forEach((n, i) => {
  if (!used.has(i)) return;
  remap.set(i, keptNames.length);
  keptNames.push(n);
});

const entries = [...book.entries()].map(([k, i]) => k + remap.get(i).toString(36));
entries.sort();

const out = `// GENERATED by tools/build-book.mjs — do not edit by hand.
//
// ${book.size} positions from ${keptNames.length} named openings
// (lichess-org/chess-openings, CC0-1.0).
//
// RAW is one entry per position: a 14-char position key followed by a base-36
// index into NAMES. It is kept as a single string rather than an object literal
// because it parses faster and takes appreciably less space.

import { bookKey } from "./book-key.js";

const NAMES = ${JSON.stringify(keptNames)};

const RAW = "${entries.join(" ")}";

let book = null;

function table() {
  if (!book) {
    book = new Map();
    for (const e of RAW.split(" ")) book.set(e.slice(0, 14), NAMES[parseInt(e.slice(14), 36)]);
  }
  return book;
}

/** "C57 Italian Game: Two Knights Defense" for a book position, else null. */
export function lookupOpening(fen) {
  return table().get(bookKey(fen)) || null;
}

export const BOOK_POSITIONS = ${book.size};
export const BOOK_OPENINGS = ${keptNames.length};
`;

writeFileSync(join(root, "overlay", "book.js"), out);
console.log(
  `${book.size} positions, ${keptNames.length} openings, ${(out.length / 1024).toFixed(0)} KB` +
    (illegal ? `, ${illegal} unplayable lines skipped` : "")
);
